"""Package the already completed v7 outputs; never retrain or change predictions."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import zipfile

README = r'''# Chakravyuh — Business Entity Resolution (v7)

Members: Kommu Hemasree (Leader), Kancharla Sunaina, Vakada Kushal, and
Vakkalanka Sai Shashank.

The submitted pipeline is the v7 positive-link rescoring cascade. It trains
baseline, v3 and v4 LightGBM classifiers on supplied labels, generates v4
preliminary predictions, and then scores every preliminary positive pair with
the frozen v4 classifier. Final thresholds are 0.65 for Source 2 and 0.75 for
Source 3. The final candidate file records precisely the pairs scored by this
last classifier. Historical scripts are included for audit; the entry point
below does not apply the rejected v5 recovery or v6 ambiguity policies.

## Environment

Tested on Windows, Python 3.13.3, with the pinned requirements. From the
extracted ZIP's `code/business_entity_resolution/` directory:

```powershell
python -m venv .venv
.\.venv\Scripts\python.exe -m pip install -r .\requirements.txt
```

After installation the pipeline operates offline, using only the supplied
challenge data. No external business lookup, geocoder, dataset or pretrained
model is used. LightGBM and the trained tree models are MIT licensed and far
below eight billion parameters; see LICENSE and licenses/.

## Complete reproduction: training, offline assessment, test predictions

DATASET must contain the original train/ and test/ directories and all seven
provided TSV files. Run from `code/business_entity_resolution/`:

```powershell
.\.venv\Scripts\python.exe -u .\src\reproduce_submission.py --data-dir "C:\path\to\student_resource\dataset" --work-root "C:\path\to\fresh_v7_reproduction" --workers 4
```

Use a new or empty work directory. The runner performs actual supervised
training, development threshold selection, independent assessment, full test
inference and validation. Both regenerated TSVs are placed in the work root's
`output/` directory. The ZIP's root output/ retains the original submission.
The runner sets the working directory for all modules and prints log paths.

To print the exact ordered commands without running them:

```powershell
.\.venv\Scripts\python.exe .\src\reproduce_submission.py --data-dir "C:\path\to\student_resource\dataset" --work-root "C:\path\to\fresh_v7_reproduction" --workers 4 --dry-run
```

Training uses 30,000 baseline references and separate 60,000-reference samples
for v3/v4. Retrieval searches all supplied Source 2/3 records. This is sampled
supervised fitting, not fitting on every labeled reference. Development uses
30,000 further references, generated by ordered 10,000 then 30,000 sampling
calls with distinct seeds. Final assessment uses 10,000 references excluding
all earlier fitting and development samples. Final inference requires the
same positive paired-improvement confidence interval guard as production.

Allow many hours and at least 45 GB free disk beyond the input data; more is
advisable. Four workers are the conservative setting used with 16 GB RAM;
large training matrices may need a pagefile. Do not run concurrent jobs in the
same work root. Inspect the stage log printed by the runner, for example:

```powershell
Get-Content "C:\path\to\fresh_v7_reproduction\artifacts_v7\finish.log" -Tail 20 -Wait
```

The runner rejects nonempty work roots to prevent mixing runs. On interruption,
inspect the failed stage log and use the individual commands printed by
--dry-run to resume. Individual inference stages checkpoint completed chunks.
Models, samples, feature matrices, indexes and logs are retained in the work
root; none must be downloaded or copied from the original developer workspace.

## Validation and offline score

From `code/business_entity_resolution/`, validate the ZIP's original outputs:

```powershell
.\.venv\Scripts\python.exe .\src\validate_streaming.py --output-dir ..\..\output --test-dir "C:\path\to\student_resource\dataset\test"
.\.venv\Scripts\python.exe .\src\validate_submission.py --matching ..\..\output\matching_results.tsv --test-dir "C:\path\to\student_resource\dataset\test" --check-ids
Get-Content .\reports_v7\metrics.json
```

Streaming validation checks both files, exact headers, every reference,
target-ID existence, duplicate-free rows/lists and match inclusion in
candidates. The unmodified official matching-file check also verifies ID
existence. Run it from this code directory to avoid automatically loading the
large candidate file; streaming validation checks that file independently.

The independent v7 macro-F0.5 is 0.9740168111 on 10,000 held-out training
references. Per-reference scoring is 1.25*TP/(0.25*true_count+predicted_count),
with 1 for a correctly empty singleton and 0 for a false merge on a singleton.
This is not the test leaderboard score. v4 achieved participant-reported
0.962; the participant selected v7, whose leaderboard score is unreported.
No 0.992 score or rank is guaranteed. France has no provided validation labels.

## Source and evidence

All source is under src/. `reproduce_submission.py` is the entry point.
`pipeline.py` and `enhanced_pipeline.py` implement the baseline and v3;
`phonetic_features.py`, `phonetic_index.py`, `phonetic_pipeline.py`, and
`hybrid_pipeline.py` implement v4. `empty_recovery.py` recreates baseline
assessment caches (its rejected recovery predictions are not submitted).
`match_rescore.py`, `calibrate_rescore.py` and `finish_rescore.py` implement
the final classifier and threshold stages. `test_pipeline.py` contains
normalization, scoring and candidate consistency checks.

models/, models_v3/ and models_v4/ contain completed trained artifacts;
reports*/ contain assessment and validation evidence. The root methodology
document is Documentation_template.md; SHA256SUMS.json covers all archived
files except itself. Supplied data and large intermediate caches are excluded.
The completed outputs cover 1,732,544 references, 5,702,473 final candidates
and 5,641,306 matches, including 259,452 France references.

Final packaging did not rerun the full training job. Original completed
training/inference evidence is included. Added orchestration preserves the
training, feature, threshold and inference definitions. Hardware/library
differences can affect retraining numerics; the archived outputs and models
are the original completed submission artifacts.
'''


def digest(path):
    with path.open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--root', type=Path, required=True)
    p.add_argument('--team', required=True)
    p.add_argument('--member', action='append', required=True)
    p.add_argument('--date', required=True)
    p.add_argument('--replace', action='store_true', help='Replace an archive created by this packager')
    a = p.parse_args()
    root = a.root.resolve()
    code = root / 'code/business_entity_resolution'
    work = root / 'artifacts_v7'
    validation = json.loads((work / 'validation_streaming.log').read_text(encoding='utf-8-sig'))
    assert validation['status'] == 'PASS'
    assert b'PASS' in (work / 'validation_official.log').read_bytes()
    safe_team = re.sub(r'[^A-Za-z0-9_-]+', '_', a.team).strip('_')
    assert safe_team
    dest = root / f'{safe_team}_submission.zip'
    if dest.exists() and not a.replace:
        raise FileExistsError(f'Preserving existing archive: {dest}')
    stage = root / 'final_submission_metadata'
    stage.mkdir(exist_ok=True)
    old_readme = code / 'README.md'
    legacy = stage / 'README_before_final_packaging.md'
    if not legacy.exists():
        legacy.write_bytes(old_readme.read_bytes())
    old_readme.write_text(README.replace(chr(92) * 2, chr(92)), encoding='utf8')
    detail = (root / 'Documentation_v7.md').read_text(encoding='utf8')
    detail = detail.replace('Team: BusinessEntityResolution (replace with registered team name). Members: not supplied.',
                            f'Team: {a.team}. Members: ' + ', '.join(a.member) + '.')
    detail = detail.replace('The revised leaderboard score is unknown until submission.',
                            'The v4 public leaderboard score was 0.962, as reported by the participant.')
    detail = detail.replace('The public/private score for v7 is unknown until organizer evaluation.',
                            'The participant selected the uploaded v7 file for final submission; its leaderboard score has not yet been supplied for this document.')
    begin = detail.index('## Exact reproduction')
    end = detail.index('## Supplementary baseline architecture')
    detail = detail[:begin] + ('## Exact reproduction\n\nUse `src/reproduce_submission.py` with the exact installation and run commands in README.md. '
        'It runs all required baseline, v3, v4, development, fresh assessment and final test stages in an empty work root, '
        'using only the supplied seven data files and this code folder. Intermediate caches are regenerated. '
        'Original completed output hashes are in SHA256SUMS.json. Packaging checks original output identity and archive integrity; '
        'a new full from-scratch training run was not performed during packaging.\n\n') + detail[end:]
    metrics = json.loads((work / 'metrics.json').read_text())
    header = f'''# ML Challenge 2026: Business Entity Resolution Solution

**Team Name:** {a.team}  
**Team Members:** {', '.join(a.member)}  
**Submission Date:** {a.date}

## 1. Executive Summary

A supervised LightGBM cascade resolves noisy business names and addresses from
the supplied records. The final v7 classifier rescores preliminary accepted
links with source-specific thresholds, exporting its exact scored candidate
set and one prediction row for every test reference.

## 2. Methodology

### 2.1 Problem Analysis

Name abbreviations, spelling/script variants, reordered or missing address
components, and ambiguous common names require multiple complementary signals.
The test set additionally contains France without training labels; country is
treated as an open string. Full dataset statistics are in reports/data_inventory.json.

### 2.2 Solution Strategy

**Approach Type:** Blocking plus supervised classifier cascade.  
**Core Innovation:** Population/competitor features, deterministic cross-script
retrieval and conservative final source-specific pair acceptance.

## 3. Candidate Generation (Blocking)

Exact/name-token/address/numeric keys and supplemental phonetic/romanized keys
reduce the full comparison space. Oversized blocks and ranked caps limit cost.
The last stage considers precisely 5,702,473 v4-positive pairs. Candidate misses
remain false negatives during assessment; perfect recall is not claimed.
Complete blocking stages, caps and the candidate audit are detailed below.

## 4. Matching Model

**Model type:** MIT-licensed LightGBM tree classifiers trained from scratch.  
**Features:** 154 final name/address similarities, token rarity/uniqueness,
numeric-order, phonetic/romanized and competing-reference signals.  
**Threshold selection:** Macro-F0.5 on 30,000 separate development references;
final thresholds 0.65 (Source 2), 0.75 (Source 3). No final-stage refitting.

## 5. Results & Error Analysis

Independent 10,000-reference macro-F0.5: {metrics['proposed']['macro_f0.5']:.10f}.
Baseline on the same references: {metrics['baseline']['macro_f0.5']:.10f}.
Missing addresses/common names can cause false merges; cross-script variation,
large-block caps and conservative final thresholds can cause missed matches.
These are offline scores; the v7 leaderboard score is not yet supplied.

## 6. Conclusion

The final cascade improves assessed precision while retaining complete test
reference coverage. Its exact final candidate inputs and measured validation
are exported for audit. Hidden-test accuracy and final ranking remain determined
by organizer evaluation.

## Appendix

### A. Code Artefacts

All source is in code/business_entity_resolution/src/. README.md provides exact
environment, training, offline evaluation, prediction and validation commands.
requirements.txt pins dependencies; model and license folders are included.

### B. Additional Results and Full Technical Methodology

'''
    doc = stage / 'Documentation_template.md'
    doc.write_text(header + detail, encoding='utf8')
    files = [(doc, 'Documentation_template.md')]
    files += [(root / 'output_v7' / name, 'output/' + name)
              for name in ('matching_results.tsv', 'candidate_pairs.tsv')]
    files += [(path, 'code/business_entity_resolution/' + path.relative_to(code).as_posix())
              for path in sorted(code.rglob('*')) if path.is_file()
              and '__pycache__' not in path.parts and '.venv' not in path.parts]
    manifest = {arc: digest(path) for path, arc in files}
    # Verify original prediction identity before building any final archive.
    prior = json.loads((root / 'SHA256SUMS_v7.json').read_text())
    for name in ('matching_results.tsv', 'candidate_pairs.tsv'):
        assert manifest['output/' + name] == prior['output/' + name]
    mf = stage / 'SHA256SUMS.json'
    mf.write_text(json.dumps(manifest, indent=2), encoding='utf8')
    files.append((mf, 'SHA256SUMS.json'))
    with zipfile.ZipFile(dest, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for path, arc in files:
            archive.write(path, arc)
    with zipfile.ZipFile(dest) as archive:
        assert archive.testzip() is None, 'ZIP CRC failure'
        assert len(archive.namelist()) == len(set(archive.namelist()))
        for arc, expected in manifest.items():
            with archive.open(arc) as stream:
                assert hashlib.file_digest(stream, 'sha256').hexdigest() == expected, arc
        assert 'not supplied' not in archive.read('Documentation_template.md').decode('utf8').lower()
    report = {'status': 'PASS', 'team': a.team, 'members': a.member,
              'selected_version': 'v7', 'leaderboard_score': None,
              'zip': str(dest), 'bytes': dest.stat().st_size, 'sha256': digest(dest),
              'files': len(files), 'output_identity_verified': True,
              'all_manifest_hashes_verified': True, 'zip_crc_checked': True,
              'source_compilation_and_tests': 'See final_submission_metadata/code_checks.log',
              'completed_output_validation': validation}
    (stage / 'package_audit.json').write_text(json.dumps(report, indent=2), encoding='utf8')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
